workflows:
  ios-testflight-workflow:
    name: iOS TestFlight Build
    instance_type: mac_mini_m1
    environment:
      flutter: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gautamramesh.glintai
    scripts:
      - name: Install Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
