// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLdWe0wPARtScIJUEdhUTtJNYHUt_0iw',
    appId: '1:73326190072:web:e01f8292116bbd5bc38a0d',
    messagingSenderId: '73326190072',
    projectId: 'focus-c6659',
    authDomain: 'focus-c6659.firebaseapp.com',
    storageBucket: 'focus-c6659.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCG2wIXF8Cg0CYDK_9UYrq9etChPYJ0Xw',
    appId: '1:73326190072:android:5cd4c55f9fae3d43c38a0d',
    messagingSenderId: '73326190072',
    projectId: 'focus-c6659',
    storageBucket: 'focus-c6659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFtb3jE7a9luheWOtZj1JOo1JD49NDmYY',
    appId: '1:73326190072:ios:75051a40dee7ac9ec38a0d',
    messagingSenderId: '73326190072',
    projectId: 'focus-c6659',
    storageBucket: 'focus-c6659.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFtb3jE7a9luheWOtZj1JOo1JD49NDmYY',
    appId: '1:73326190072:ios:75051a40dee7ac9ec38a0d',
    messagingSenderId: '73326190072',
    projectId: 'focus-c6659',
    storageBucket: 'focus-c6659.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHLdWe0wPARtScIJUEdhUTtJNYHUt_0iw',
    appId: '1:73326190072:web:22c435fa87c35266c38a0d',
    messagingSenderId: '73326190072',
    projectId: 'focus-c6659',
    authDomain: 'focus-c6659.firebaseapp.com',
    storageBucket: 'focus-c6659.firebasestorage.app',
  );
}
